### ISSUE TITLE
Upgrade postcss-values-parser dep to v3 to remove deprecated package message

### ISSUE THREAD

**Issue by marcofugaro** [csstools/postcss-color-mod-function#35]
Currently when using this plugin, this appears in the console.

> postcss-color-mod-function > postcss-values-parser > flatten@1.0.2: I wrote this module a very long time ago; you should use something else.

This was already solved in https://github.com/shellscape/postcss-values-parser/issues/86, upgrading the dependency would solve the issue.

**Comment by feimosi** [comment]
Agreed, same here, would be great to have this package upgraded.

**Comment by Twissi** [comment]
yes, `postcss-values-parser` should be bumped to version 3.0.5.
I can easily do that, but how can I make sure the update doesn't breaks anything?

**Comment by carlosjeurissen** [comment]
This would indeed be very welcome. @Twissi seems this package already has tests.

**Comment by romainmenke** [comment]
`postcss-values-parser` had been dropped in favor of `postcss-value-parser`
