### ISSUE TITLE
Recommendation alternative to color-mod

### ISSUE THREAD

**Issue by FernandoBasso** [csstools/postcss-color-mod-function#36]
Since color-mod spec dead, is there any replacement recommendation that PostCSS should/could point users to?

If I understand PostCSS correctly, it is intended to be spec-compliant, and in that case, no recommendation would make sense if no spec is currently being worked on for color stuff. Is that the case or the docs could point to some alternatives or recommendations?

**Comment by 0gust1** [comment]
Same here. We would like to use postCSS instead of SASS for our design-system / component lib.
Color functions are a must-have :-/

**Comment by TheComputerM** [comment]
You could define custom color functions using https://github.com/andyjansson/postcss-functions

**Comment by AlexWayfer** [comment]
I guess, this issue can be closed in favor of #37.

**Comment by romainmenke** [comment]
see : 
- https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-relative-color-syntax
- https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-color-mix-function
