### ISSUE TITLE
New color manipulation functions from Color Module 5

### ISSUE THREAD

**Issue by equinusocio** [csstools/postcss-color-mod-function#37]
The new [Color Module 5 working draft](https://www.w3.org/TR/css-color-5) introduce new css functions to manipulate colors:

- [`color-adjust()`](https://www.w3.org/TR/css-color-5/#coloradjust)
- [`color-mix()`](https://www.w3.org/TR/css-color-5/#colormix)
- [`color-contrast()`](https://www.w3.org/TR/css-color-5/#colorcontrast)

Would you consider to "revive" this plugin (or make new ones) in order to support the new spec?

**Comment by onigoetz** [comment]
it seems that this proposal was dropped as well : https://github.com/w3c/csswg-drafts/issues/6179#issuecomment-871569914

**Comment by AlexisWalravens** [comment]
- color-mix
- color-contrast
- relative color

Are still in the spec and even in Safari TP 122

**Comment by equinusocio** [comment]
> it seems that this proposal was dropped as well : https://github.com/w3c/csswg-drafts/issues/6179#issuecomment-871569914

Yes they are replace by relative colors, which are a bit harder to polyfill i guess

**Comment by romainmenke** [comment]
We are first catching up with css-color-4 : https://github.com/csstools/postcss-plugins/pull/70

New plugins will be added for css-color-5 functions after that effort.

**Comment by Martinomagnifico** [comment]
Would love to see relative colors polyfilled!

**Comment by equinusocio** [comment]
@romainmenke How is doing. Got any plan about this?

**Comment by romainmenke** [comment]
Not at this time.

Our current focus is on shipping `postcss-preset-env` version 8 : https://github.com/csstools/postcss-plugins/pull/472

-----

This plugin is also definitely abandoned.
I generally do not follow up on anything outside the mono repo (csstools/postcss-plugins)

The issue to subscribe to for updates is this one : https://github.com/csstools/postcss-plugins/issues/177

----

We do accept sponsorships :)
This might help us spend more time on all this.

**Comment by equinusocio** [comment]
Ty

**Comment by romainmenke** [comment]
see : 
- https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-relative-color-syntax
- https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-color-mix-function
