### ISSUE TITLE
Release with PostCSS 8 compatibility

### ISSUE THREAD

**Issue by alexlafroscia** [csstools/postcss-color-mod-function#39]
It seems like a PR was made for PostCSS 8 compatibility (#38) but a release hasn't been made since then.

Is there any chance we can get a release cut, for those that are trying to migrate to PostCSS 8?

**Comment by alexlafroscia** [comment]
Just to scratch my own itch, I pushed a `4.0.0` of this package under my own username on `npm`

https://www.npmjs.com/package/@alexlafroscia/postcss-color-mod-function

**Comment by nolimitdev** [comment]
I using postcss-color-mod-function@3.0.3 with latest webpack v5.64.2 and latest postcss v8.3.11 and it seem it is working well with PostCSS 8. Or Im missing something?

**Comment by romainmenke** [comment]
Support for PostCSS 8.0.0 has be released as  `v4.0.0`

Thank you for your patience 😅
